# Generated by Django 4.1.4 on 2022-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_list_date_alter_list_url_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
