# Generated by Django 4.1.4 on 2022-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
