# Generated by Django 4.1.4 on 2022-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_list_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
