# Generated by Django 4.1.4 on 2022-12-21 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_user_alter_bid_user_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchuser', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchproduct', to='auctions.list')),
            ],
        ),
    ]
