# Generated by Django 4.1.4 on 2022-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='close',
            field=models.IntegerField(default=0),
        ),
    ]
