# Generated by Django 4.1.4 on 2022-12-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_list_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.CharField(blank=True, choices=[('ele', 'Electronics'), ('to', 'Toys'), ('fa', 'Fashion'), ('fu', 'Furnitures'), ('be', 'Beauty, health, and household care'), ('other', 'Others')], max_length=50),
        ),
    ]
