# Generated by Django 4.1.4 on 2022-12-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
